# Generated by Django 4.2.7 on 2023-11-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cor',
            field=models.TextField(default='blank', max_length=255),
        ),
    ]
