# Generated by Django 4.2.7 on 2023-11-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0003_usuario_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='gen',
            field=models.TextField(default='blank', max_length=255),
        ),
    ]
