# Generated by Django 4.2.7 on 2023-11-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0004_usuario_gen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='forn',
            field=models.TextField(default='blank', max_length=255),
        ),
    ]
