# Generated by Django 4.2.7 on 2023-11-06 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0005_usuario_forn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nome',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='idade',
            new_name='valor',
        ),
    ]
